[package]
name = "contingram-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.12"
contingram = { path = ".." }

[[bin]]
name = "contract"
path = "fuzz_targets/contract.rs"
test = false
doc = false
bench = false

[[bin]]
name = "report"
path = "fuzz_targets/report.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
